name: My First Workflow

on: push 
jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo "my first github actions job"

            - name: List files
              run: ls -ltra

            - name: check repository
              uses: actions/checkout@v4

            - name: read README
              run: cat README.md
            
            